### ISSUE TITLE
Error message after install

### ISSUE THREAD

**Issue by andi1337-i** [Scrounger/ioBroker.linkeddevices#23]
After installing the Adapter i get the following error message as a popup (see image).

To reproduce the error message, I click on settings-symbol for linkeddevices in Instances-Tab.

I guess its just a typo :)

Thanks,
Andi
<img width="686" alt="Bildschirmfoto 2019-09-25 um 11 59 20" src="https://user-images.githubusercontent.com/55757339/65591101-2c1ca100-df8c-11e9-9c4b-8782b3cd5ff7.png">

**Comment by Scrounger** [comment]
Which version do you use?
Whiche browser do you use?
Which admin, npm, js-controller, node version do you use?

**Comment by andi1337-i** [comment]
Hi Scrounger,

thank you for your response.

Sorry for not providing the necessary information - as i am a software-tester myself, this is not a good way to raise an issue.

Here are the missing information:

LinkedDevices: 1.0.0
NPM: 6.11.3
Admin: 3.6.2
Node: 10.15.2
JS-controller: 1.5.14

I just reinstalled the adapter again and the error message is gone now.. so maybe there was an issue with the installing procedure (tried it two times before writing the issue-request with no luck).

So maybe the error is already fixed.

Best regards
Andi

**Comment by Scrounger** [comment]
ok, so i close this
