### ISSUE TITLE
Bitte Text anpassen

### ISSUE THREAD

**Issue by ldittmar81** [Scrounger/ioBroker.linkeddevices#29]
Prinzipiell haben wir kein Problem damit, dass ein Entwickler, der sich Mühe gibt was zu entwickeln und seine Freizeit opfert, eine kleine Anerkennung bekommt, aber wenn ein solchen Link eingebaut wird, muss es klar ersichtlich sein an wem das Geld geht. Mit "uns" gehen alle User davon aus, dass die Spende an das ioBroker-Team geht. Hier bitte dein Text so anpassen, so dass es ersichtlich ist, dass die Spende an den Entwickler des ioBroker.linkeddevices Adapters geht. Danke!

Irgendwie so: Dir gefällt der Adapter? Dann unterstütze den Adapterentwickler (Scrounger) doch mit einer kleinen Spende. (Die Spende geht direkt an den Entwickler, der auch für den Spendenaufruf allein verantwortlich ist.)

![28-10-_2019_08-48-55](https://user-images.githubusercontent.com/9552828/67661504-b24c4e80-f961-11e9-9f9f-77f5966950c2.png)

![28-10-_2019_09-11-38](https://user-images.githubusercontent.com/9552828/67662111-00ae1d00-f963-11e9-933c-138dd509ab43.png)

**Comment by Scrounger** [comment]
Alles klar, pass ich entsprechend an

**Comment by ldittmar81** [comment]
Danke!! Und übrigens: toller Adapter! Ich nutze es in Verbindung mit dem ioBroker.devices. Echt super Arbeit :-)

**Comment by Scrounger** [comment]
@ldittmar81 

In bc41c484013cd1a9373266f16cea15b8d39c2d45 enthalten.

Allerdings hab ich den Zusatz _(Die Spende geht direkt an den Entwickler, der auch für den Spendenaufruf allein verantwortlich ist.)_ nicht mit eingebaut, weil ich finde das der Text dann aufdringlich wird.

Solltet Ihr allerdings diesen Zusatz unbedingt wollen, so bau ich das natürlich noch mit ein.
