### ISSUE TITLE
Safari Browser: Fehler bei der Adapterkonfiguration

### ISSUE THREAD

**Issue by DanyelAndre** [Scrounger/ioBroker.linkeddevices#30]
Erstmal danke für diesen spitzenmäßigen Adapter. Der macht das Leben bei Änderungen deutlich leichter. Allerdings bekomme ich ihn nicht vollständig zum laufen.

Wenn ich die Instanz konfigurieren möchte, kommt sofort diese Fehlermeldung:

![Bildschirmfoto 2020-01-25 um 09 56 42](https://user-images.githubusercontent.com/33354462/73118783-2eeacb00-3f59-11ea-9ce1-cd37c8c7fc28.jpg)

Auch die Erzeugung des Skripts für die Variablen aller verlinkten Objekte funktioniert nicht.

JavaScript Enginge ist installiert.

**Comment by Scrounger** [comment]
erstell mal ein linkedobject, dann müsste die fehlermeldung nicht mehr kommen

**Comment by DanyelAndre** [comment]
Ich habe schon mehrere verlinkte Objekte erstellt und die arbeiten auch. Fehlermeldung kommt leider trotzdem noch. Wenn ich es richtig verstanden habe ist die Konfiguration dafür wichtig, dass spätere Änderungen einfach durchführbar sind?

**Comment by Scrounger** [comment]
welche npm verison?
welche nodejs version?
welchen js-controller version?

**Comment by DanyelAndre** [comment]
Eins vorweg: ich habe null Programmierkenntnisse und fuchse mich gerade in ioBroker hinein. Werde versuchen, Deine Fragen so gut wie möglich zu beantworten:

npm: 6.13.4
nodejs: 10.18.1
Script Engine (ist das der js-controller?): 4.1.12
Browser: Safari 12.1.2

**Comment by Scrounger** [comment]
> Script Engine (ist das der js-controller?): 4.1.12

Nein was steht unter hosts für ne version?

**Comment by DanyelAndre** [comment]
Das war jetzt anstrengend weil ich erst herausfinden musste, dass die Hosts ausgeblendet waren.

js-controller ist v2.1.1

**Comment by Scrounger** [comment]
Kannst du das mal mit nem anderen browser testen, z.B. firefox oder chrome?

**Comment by DanyelAndre** [comment]
Ui...das ist's gewesen. In Chrome ist alles tutti. Da muss man erstmal drauf kommen.

Safari ist mein Hauptbrowser. Wird das irgendwann auf Safari funktionieren oder muss ich mich auf Chrome umgewöhnen?

Danke schonmal für Deine zügige Hilfe!

**Comment by Scrounger** [comment]
Ich hab kein Safari. von daher kann ich das nicht testen.
Kannst du mal schauen was in der browser console steht wenn du die config öffnest.

**Comment by DanyelAndre** [comment]
![Bildschirmfoto 2020-01-25 um 16 56 54](https://user-images.githubusercontent.com/33354462/73123762-d258d180-3f93-11ea-89ca-635ae9370320.jpg)
![Bildschirmfoto 2020-01-25 um 16 57 08](https://user-images.githubusercontent.com/33354462/73123763-d2f16800-3f93-11ea-91d8-eced173748a8.jpg)
