### ISSUE TITLE
wrong link to docs

### ISSUE THREAD

**Issue by kneisel** [Scrounger/ioBroker.linkeddevices#34]
**Describe the bug**  
You've changed the directory name "doc" to "docs" and should change the link in e.g. readme.md

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by ldittmar81** [comment]
https://github.com/Scrounger/ioBroker.linkeddevices/pull/35

**Comment by Scrounger** [comment]
Danke!

**Comment by kneisel** [comment]
Danke selbst ;-)
