### ISSUE TITLE
Feature request - Groups or ability to link multiple datapoint into one

### ISSUE THREAD

**Issue by rogerroger-coder** [Scrounger/ioBroker.linkeddevices#37]
Hi,
it would be nice to be able link multiple datapoints of the same type into one linked device.
By using defined functions like min, max, median, latest.

My use case would be the unifi adapter which has a datapoint "last_seen" for any connected device.
To get a "anyone_last_seen" I would link them using "max" so the latest timestamp of all the devices would be linked to "anyone_last_seen". 

Just as an idea :)
Anyhow great work 👍

**Comment by Scrounger** [comment]
sorry not possible, because of concept of adapter.
