### ISSUE TITLE
Umrechnung für verlinktes Objekt

### ISSUE THREAD

**Issue by r748** [Scrounger/ioBroker.linkeddevices#40]
Wäre es möglich, bei den Operatoren für verlinke Objekte auch "+" und "-" zuzulassen? Ich hätte gerne bei gewissen Objekten den Umkehrwert berechnet. Meine Z-Wave Rollos sind mit 99 ganz hoch- und mit 0 ganz runtergefahren. Ich möchte aber 0 für geöffnet und 99, bzw. 100 für geschlossen haben, sprich folgende Umrechnung: WERT * 100 / 99 * (-1) + 100.

**Comment by Scrounger** [comment]
Das geht, aber nur für objekte vom teyp number read only.

Bei write objekte ist das nicht möglich, weil man nicht einfach den Kehrwert berechnen kann.
Es gibt zwei Wege Objekte ändert sich -> linkeddevices Objekt ändert sich mit Formel WERT * 100 / 99 * (-1) + 100.
Zweiter Weg linkedevices Objekt änder sich -> Objekt ändert sich mit 1 / WERT * 100 / 99 * (-1) + 100. Da kommt aber nicht das selbe raus.
