### ISSUE TITLE
Linked device in erster Zeile - nicht editierbar

### ISSUE THREAD

**Issue by FRYYYYYY** [Scrounger/ioBroker.linkeddevices#41]
Hallo! :-)

Wenn ich die Verlinkung der Devices in den Adapteroptionen "trenne", kann ich diese auch über den "Link" Button wieder zu einem Objekt hinzufügen.
Das funktioniert aber nicht beim ersten Eintrag in der Liste, erst ab dem zweiten.

**Comment by Scrounger** [comment]
Kann ich nicht reproduzieren. Was steht in der browser console (F12) wenn du die Zuweisung machst?

**Comment by FRYYYYYY** [comment]
Vielleicht muss ich das noch weiter präzisieren: Ich kann den Link aufheben, danach neu verknüpfen, aber die Spalte "verlinkt mit" bleibt leer:

![image](https://user-images.githubusercontent.com/13643787/85222871-baf50780-b3be-11ea-9b24-d624c7bc3752.png)

Konsole sagt:

![image](https://user-images.githubusercontent.com/13643787/85222884-cba57d80-b3be-11ea-8a32-b3c9033c0447.png)
![image](https://user-images.githubusercontent.com/13643787/85222894-d5c77c00-b3be-11ea-8b31-82cceb2f5ff7.png)
![image](https://user-images.githubusercontent.com/13643787/85222900-e0821100-b3be-11ea-8c54-dd026ba04bd9.png)

**Comment by Scrounger** [comment]
Und du hast exakt nur ein Element in der Tabelle?

**Comment by FRYYYYYY** [comment]
Nein, 10 bis 20. Habe nur von da einen Screenshot gemacht. :-)

**Comment by Scrounger** [comment]
inzwischen behoben
