### ISSUE TITLE
Leerzeichen 

### ISSUE THREAD

**Issue by theip4nda** [Scrounger/ioBroker.linkeddevices#42]
Es können auch Namen mit Leerzeichen vergeben werden. Dadurch compiled Java keine Scripte mehr und viele meiner Scripte haben nicht mehr funktioniert.

Herr Dittmar sagte mir, das man keine Objectnamen mit Leerzeichen erstellen darf, was ich nicht wusste.

Bitte das Script so abändern das keine Verlinkungen mehr mit Leerzeichen erstellt werden können.

Danke

**Comment by Scrounger** [comment]
Welches Skript meinst du?

Meines Wissens nach sind leerzeichen erlaubt, siehe:
https://forum.iobroker.net/topic/12554/wichtige-%C3%A4nderung-objekt-state-id-bezeichner-d%C3%BCrfen-keine-oder-mehr-enthalten
