### ISSUE TITLE
linkeddevices are dropping smartnames for iot Adapter

### ISSUE THREAD

**Issue by ak1de** [Scrounger/ioBroker.linkeddevices#43]
Please have a look at
https://forum.iobroker.net/topic/34420/troubleshooting-iot-smart-devices-linkeddevices-hm-rpc

Basically when I add a smart device based on a linkeddevices object which is then linked to a Homematic devices, the information (smartname, etc) gets correctly into the Raw data for the linkeddevices object.

Once I am rebooting the ioBroker host OS, the smartdevice information seems to get lost from the raw data of the linkeddevices object. Hence the smart device gets lost in the iot adapter, too.

I observed this with all (about 10-12) Homematic devices I tried to include as smart devices in this way. It did not happen with 3 Shelly devices I included in the same manner.

iot: 1.5.3
linkeddevices: 1.1.4
hm-rpc: 1.14.9
node and node.js: 12.16.3
npm: 6.14.4

Best regards,
Stefan

**Comment by Scrounger** [comment]
gelöst, details siehe https://forum.iobroker.net/topic/34420/gel%C3%B6st-troubleshooting-iot-smart-devices-linkeddevices/2
