### ISSUE TITLE
Object is invalid Meldung

### ISSUE THREAD

**Issue by daniel-lo** [Scrounger/ioBroker.linkeddevices#44]
v1.1.4
Da steht reporten .. also reporte ich. Nach einem Neustart im Log gefunden .. nach "Reparatur" keine Änderung:

linkeddevices.0 | 2020-07-07 06:59:04.299 | info | (22477) [initialObjects] finished
-- | -- | -- | --
linkeddevices.0 | 2020-07-07 06:59:04.293 | info | (22477) [createAllLinkedObjects] count of active linkedObjects: 2
linkeddevices.0 | 2020-07-07 06:59:04.258 | info | (22477) [createLinkedObject] linked object  'alexa2.0.Echo-Devices.G091470400150342.Commands.speak' (string) to  'linkeddevices.0.echo_wohnzimmer.ACTUAL' (state)
linkeddevices.0 | 2020-07-07 06:59:04.203 | warn | (22477) This object will not be created in future versions. Please report this to the developer.
linkeddevices.0 | 2020-07-07 06:59:04.203 | warn | (22477) Object linkeddevices.0.echo_wohnzimmer.ACTUAL is invalid:  obj.common.type has an invalid value (state) but has to be one of  number, string, boolean, array, object, mixed, file, json
linkeddevices.0 | 2020-07-07 06:59:04.189 | info | (22477) [createLinkedObject] linked object  'alexa2.0.Echo-Devices.G0913L05924404UQ.Commands.speak' (string) to  'linkeddevices.0.echo_schlafzimmer.ACTUAL' (state)
linkeddevices.0 | 2020-07-07 06:59:04.099 | warn | (22477) This object will not be created in future versions. Please report this to the developer.
linkeddevices.0 | 2020-07-07 06:59:04.099 | warn | (22477) Object linkeddevices.0.echo_schlafzimmer.ACTUAL is invalid:  obj.common.type has an invalid value (state) but has to be one of  number, string, boolean, array, object, mixed, file, json
linkeddevices.0 | 2020-07-07 06:59:03.656 | warn | (22477) This object will not be created in future versions. Please report this to the developer.
linkeddevices.0 | 2020-07-07 06:59:03.655 | warn | (22477) Object linkeddevices.0.echo_wohnzimmer.ACTUAL is invalid:  obj.common.type has an invalid value (state) but has to be one of  number, string, boolean, array, object, mixed, file, json
linkeddevices.0 | 2020-07-07 06:59:03.646 | warn | (22477) This object will not be created in future versions. Please report this to the developer.
linkeddevices.0 | 2020-07-07 06:59:03.646 | warn | (22477) Object linkeddevices.0.echo_schlafzimmer.ACTUAL is invalid:  obj.common.type has an invalid value (state) but has to be one of  number, string, boolean, array, object, mixed, file, json
linkeddevices.0 | 2020-07-07 06:59:03.607 | info | (22477) [initialObjects] started...
linkeddevices.0 | 2020-07-07 06:59:03.589 | info | (22477) starting. Version 1.1.4 in /opt/iobroker/node_modules/iobroker.linkeddevices, node: v10.21.0, js-controller: 3.1.6

**Comment by Scrounger** [comment]
Stell bitte die raw daten von `alexa2.0.Echo-Devices.G0913L05924404UQ.Commands.speak` und `linkeddevices.0.echo_schlafzimmer.ACTUAL` zur Verfügung

**Comment by daniel-lo** [comment]
{
  "from": "system.adapter.alexa2.0",
  "user": "system.user.admin",
  "ts": 1600197263435,
  "common": {
    "name": "speak",
    "role": "media.tts",
    "type": "string",
    "read": true,
    "write": true,
    "custom": {
      "linkeddevices.0": {
        "name": "echo schlafzimmer speak",
        "role": "state",
        "string_convertTo": "state",
        "enabled": true,
        "linkedId": "echo_schlafzimmer.ACTUAL",
        "expertSettings": true
      }
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "alexa2.0.Echo-Devices.G0913L05924404UQ.Commands.speak",
  "type": "state"
}
###########################################################################
{
  "type": "state",
  "common": {
    "role": "state",
    "type": "state",
    "read": true,
    "write": true,
    "name": "echo schlafzimmer speak",
    "custom": {
      "linkeddevices.0": {
        "enabled": true,
        "parentId": "alexa2.0.Echo-Devices.G0913L05924404UQ.Commands.speak",
        "parentType": "string",
        "isLinked": true
      }
    },
    "icon": "linkeddevices_small.png",
    "desc": "Created by linkeddevices"
  },
  "native": {},
  "from": "system.adapter.linkeddevices.0",
  "user": "system.user.admin",
  "ts": 1600197309310,
  "_id": "linkeddevices.0.echo_schlafzimmer.ACTUAL",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by Scrounger** [comment]
closed because of inactivty
