### ISSUE TITLE
Object will not be created in future

### ISSUE THREAD

**Issue by daniel-lo** [Scrounger/ioBroker.linkeddevices#46]
Ich soll dem Entwickler was melden ...

linkeddevices.0 | 2020-09-10 19:56:25.878 | info | (11629) [onObjectChange] count of active linkedObjects: 2
-- | -- | -- | --
linkeddevices.0 | 2020-09-10 19:56:25.877 | info | (11629)  [createLinkedObject] linked object  'alexa2.0.Echo-Devices.G0913L05924404UQ.Commands.speak' (string) to  'linkeddevices.0.echo_schlafzimmer.ACTUAL' (state)
linkeddevices.0 | 2020-09-10 19:56:25.823 | warn | (11629) This object will not be created in future versions. Please report this to the developer.
linkeddevices.0 | 2020-09-10 19:56:25.822 | warn | (11629)  Object linkeddevices.0.echo_schlafzimmer.ACTUAL is invalid:  obj.common.type has an invalid value (state) but has to be one of  number, string, boolean, array, object, mixed, file, json
linkeddevices.0 | 2020-09-10 19:56:25.818 | info | (11629) [onObjectChange] parentObject 'alexa2.0.Echo-Devices.G0913L05924404UQ.Commands.speak' properties changed

**Comment by Scrounger** [comment]
Stell bitte die raw daten von `alexa2.0.Echo-Devices.G0913L05924404UQ.Commands.speak` und `linkeddevices.0.echo_schlafzimmer.ACTUAL` zur Verfügung

**Comment by Scrounger** [comment]
closed because of inactivty
