### ISSUE TITLE
Objekte (Shutter) funktionieren nicht im iot Adapter

### ISSUE THREAD

**Issue by LJSven** [Scrounger/ioBroker.linkeddevices#48]
Ich versuche über "intelligente Aufzählungen" Shutter vom Shelly in den iot Adapter zu bekommen. Allerdings werden keine Geräte gefunden. Was mache ich falsch?

`{
  "from": "system.adapter.linkeddevices.0",
  "user": "system.user.admin",
  "ts": 1600426986556,
  "common": {
    "name": "EG_HWR_Rollade_Fenster",
    "type": "number",
    "role": "level.blind",
    "unit": "%",
    "desc": "Created by linkeddevices",
    "min": 0,
    "max": 100,
    "read": true,
    "write": true,
    "smartName": false,
    "custom": {
      "linkeddevices.0": {
        "enabled": true,
        "parentId": "shelly.0.SHSW-21#32BE5B#1.Shutter.Position",
        "parentType": "number",
        "isLinked": true
      }
    },
    "icon": "linkeddevices_small.png"
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "linkeddevices.0.Shutter.EG.EG_HWR_Rollade_Fenster.Position",
  "type": "state"
}`

![Bildschirmfoto 2020-09-21 um 12 39 35](https://user-images.githubusercontent.com/8560588/93757737-8b48dc00-fc07-11ea-9bf2-3c5cdf4bc6c0.png)

**Comment by Scrounger** [comment]
siehe #53
