### ISSUE TITLE
IoT adapter doesn't understand LinkedDevices datapoints

### ISSUE THREAD

**Issue by Xyolyp** [Scrounger/ioBroker.linkeddevices#5]
I'm using the LinkedDevices Adapter version 0.3.0 and IoT Adapter version 0.4.3 (stable) to trigger Logitech Harmony Scenes. The Harmony Adapter offers datapoints as numerics (0 for off, 1 for starting 2 for running) and I used the LinkedDevices adapter to convert that to a boolean. 
This boolean works as intended but when I try to add the LinkedDevices boolean datapoint in the IoT Adapter I get the message:
`"linkeddevices.0.Harmony.Fernseher" not exists or no native part.`
The datapoint does exist and work as intended if the value is changed manually. Please add the "native part" whatever that means.

**Comment by Scrounger** [comment]
https://forum.iobroker.net/topic/24088/linked-devices-datenpunkt-mit-iot-adapter

Hab deinen Post schon gesehen, deshalb antworte ich auf Deutsch.
Schau ich mir an, hab selbst ne harmony und kann es entsprechend testen

**Comment by Scrounger** [comment]
Bug Fix ist in e669b98 enthalten.
Bitte testen und Rückmeldung geben, damit wir das Ticket schließen können.

**Comment by Xyolyp** [comment]
Vielen Dank für die schnelle Umsetzung! Die ersten Tests sind erfolgreich und es funktioniert bisher.
