### ISSUE TITLE
Unable to add a "SPACE" in the "prefix for id of linked object" field

### ISSUE THREAD

**Issue by louisvangeldrop** [Scrounger/ioBroker.linkeddevices#52]
Unable to add a "space" in the "prefix for id of linked object" field 

1. Open the settings field of a State object
2. Try to add: "philips hue" in the "prefix for id of linked object" field 

![image](https://user-images.githubusercontent.com/10716245/100391364-776c8c80-3033-11eb-814b-d717f8a6987c.png)

3. Error. See picture

![image](https://user-images.githubusercontent.com/10716245/100391326-599f2780-3033-11eb-9537-6e79647bcd1b.png)

4. It is not allowed to enter a SPACE in this field. Adding a SPACE was allowed until recently.

Linkeddevices Version:
![image](https://user-images.githubusercontent.com/10716245/100391556-1e512880-3034-11eb-937c-8fca858718c7.png)

**Comment by Scrounger** [comment]
this correct. Space is not allowed anymore
