### ISSUE TITLE
iot-Adapter verliert die zuordnung beim Neustart von linkeddevices

### ISSUE THREAD

**Issue by guergen1** [Scrounger/ioBroker.linkeddevices#53]
**Describe the bug**  
Wenn das System neustartet oder der linkeddevices-Adapter neu gestartet wird, verliert der iot-Adapter die Geräte

**To Reproduce**  
1. iot-Adapter anwählen, neues Gerät eibfügen und speichern
2. linkeddevices-Adapter neustarten
3. iot-Adapter Einstellungen überprüfen
4. alle Geräte, die über den linkeddevices auf die Geräte verweisen sind weg

**Expected behavior**  
Die Geräte sollten noch da sein, nach neustart

**Screenshots & Logfiles**  
keine Einträge im Log

**Versions:**  
 - Adapter version: 1.4.0
 - JS-Controller version: 3.1.6 
 - Node version: 12.20.0 
 - Operating system: Debian

**Comment by Scrounger** [comment]
https://forum.iobroker.net/topic/34420/gel%C3%B6st-troubleshooting-iot-smart-devices-linkeddevices
