### ISSUE TITLE
Error only numbers and math operators allowed

### ISSUE THREAD

**Issue by Greiler21** [Scrounger/ioBroker.linkeddevices#55]
English: 
Error only numbers and math operators allowed is always dipslayed if something other than 
* or / is typed in the field for "Conversion for linke object"

Deutsch:
Ich würde gerne eine verlinktes Objekt für ein Rollo anlegen und dabei die Umrechnung zum invertieren der Position in Prozente nutzen. 
Das verlinkte Objekt ist vom Typ "Zahl". Sobald ich die mathematische Formel zum invertieren eingebe erscheint die oben genannte Fehlermeldung.

Meine Formel wäre: *(-1)+100 ( leichter wäre: 100 - obj.val aber ich denke so funktioniert die Syntax nicht da ich ja keine Variable des Objekt in der Umrechnung mitgegeben bekomme.)

Der Fehler erscheint sowohl in der Version 1.2.2 also auch 1.4.0

**Comment by Scrounger** [comment]
das geht nur bei read only states.
Hintergrund ist, dass bei write/read states der kehrwert gebildet werden muss und das geht wenn man nur multiplikation / division drin hat.
