### ISSUE TITLE
Problem with SQL Settings in combination with Linkeddevices

### ISSUE THREAD

**Issue by twobeass** [Scrounger/ioBroker.linkeddevices#57]
**Describe the bug**  
After opening the SQL Settings from a Datapoint i just get the Message "undefined" 
This seems to be a problem coming from linkeddevices adapter, cause if i downgrade to 1.2.2 the problem is gone... 

**To Reproduce**  
1. Go to a datapoint
2. Click on settings
3. Scroll down to sql

**Expected behavior**  
I expected the settings to open

**Screenshots & Logfiles**  
Here you can see the result
![image](https://user-images.githubusercontent.com/4639195/102224429-3a830f80-3ee6-11eb-96a2-72964ae44af2.png)

**Versions:**  
 - Adapter version: problems after 1.2.2
 - iobroker.sql: 1.15.3
 - JS-Controller version: 3.1.6
 - Node version: 10.23.0
 - Operating system: Raspian Buster

**Comment by Pendora2017** [comment]
Same error to me with a combination of lovelace (v1.3.3)
![1607250122905-fehler](https://user-images.githubusercontent.com/28994273/102367359-f8c39900-3fb9-11eb-884b-e5accdb7a25d.png)

LinkedDevices Adapter with this Bug: v1.4.0
LinkedDevices Adapter without this Bug: v1.2.1

- NodeJS: v12.20.0
- JS Controller: 3.1.6
- OS: Ubuntu 20

**Comment by twobeass** [comment]
thanks a lot for fixing!
