### ISSUE TITLE
Übernimmt Custom Settings in Linked Devices

### ISSUE THREAD

**Issue by Omega236** [Scrounger/ioBroker.linkeddevices#58]
Jeder verlinkte Datenpunkt übernimmt alle Custom-Settings vom Original Objekt.
Dadurch werden auch vom verlinktem Objekt z.B. alles nochmal in SQL geloggt und noch viele andere Adapter machen etwas doppelt/ungewollt

Verlinkte Datenpunkte sollten die Custom-Settings nicht übernehmen.

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

 - Adapter version: 1.4.1
 - JS-Controller version: 3.1.6
 - Node version:  v12.20.0
 - Operating system: Docker Linux x86

**Comment by Scrounger** [comment]
So ist das Konzept, Datenpunkt werden 1:1 gespiegelt inkl. der custom settings.

Normalerweise sollte man wenn ein Datenpunkt angelegt ist, direkt einen linked Datenpunkt erstellen und alle custom settings nur bei diesem setzen. Hintergrund ist, wenn die Hardware mal defekt ist, muss man nur den linked Datenpunkt mit dem Datenpunkt der neuen HW mappen und alles funktioniert wieder. Custom settings beim orginalen Datenpunkt gehen in diesem Fall komplett verloren!

**Comment by Omega236** [comment]
Ok stimmt , da hast du natürlich recht
