### ISSUE TITLE
Number conversion for hue lights doesn't work as expected

### ISSUE THREAD

**Issue by cored0wn** [Scrounger/ioBroker.linkeddevices#60]
**Describe the bug**  
I created a linked device for my hue lights as described in your documentation. When I change the value of an hue light bulb in the hue adapter it works fine, but when I change the value of the brightness in your adapter to 45 for example the conversion (*100/255) produces 114.75. But this value won't be accepted by bulb because of its decimal places.

**To Reproduce**  
1. Go to 'linkeddevices.0.Licht.Wohnzimmer.Kugel_Licht', which is my linkeddevices node for my light bulb
2. Change value to '45'
3. Scroll down to 'hue-extended.0.lights.045-kugel_weis_wohnzimmer.action.brightness'
4. See error (value '114.75')

**Expected behavior**  
The adapter should remove the decimal places on both sides, as far as it is configured. Additionally an option "Convert according to function" would be useful.

**Versions:**  
 - Adapter version: 1.4.2
 - JS-Controller version: 3.1.6
 - Node version: 12.20.0
 - Operating system: Raspberry Pi OS Kernel version 5.4.79-v7l+

**Comment by cored0wn** [comment]
I found the relevant code line: https://github.com/Scrounger/ioBroker.linkeddevices/blob/ad3f593cfd2c5a43ca8df3de69a8ef18876fd290/main.js#L1469

I'm not sure why you check if its the target object value which will be changed. But if there's no reason for this you could easily remove the corresponding if-statement and fix the issue.

**Comment by cored0wn** [comment]
Pull request created #61

**Comment by cored0wn** [comment]
#61

**Comment by Scrounger** [comment]
> But this value won't be accepted by bulb because of its decimal places.

Which Adapter sends the values to the bulb?
At my point of view, this should be handled by the adapter it self. If the user input is not correct for exampl decimal places are wrong, the adapter should convert this value to a value that can handled by the devices.
So please write an issue for the corresponding adapter.

> I found the relevant code line:
> 
> https://github.com/Scrounger/ioBroker.linkeddevices/blob/ad3f593cfd2c5a43ca8df3de69a8ef18876fd290/main.js#L1469
> 
> I'm not sure why you check if its the parent object value which will be changed. But if there's no reason for this you could easily remove this part from the condition and fix the issue.

Reason is that the max decimal plaes only applies to the linked object. All settings are only for the linked objects
