### ISSUE TITLE
Admin 5: verlinkte Objekte werden nicht angezeigt

### ISSUE THREAD

**Issue by guergen1** [Scrounger/ioBroker.linkeddevices#69]
Nach dem Update auf Admin 5 werden nicht alle verlinkten Objekte als verlinkt angezeigt:
![Aufnahme_2021_05_23_12_06_58_231](https://user-images.githubusercontent.com/34395245/119256197-cef14c80-bbbf-11eb-836e-a88a21751036.gif)

Node.js: 12.22.1
NPM: 6.14.12
JS-controller: 3.3.10

**Comment by Scrounger** [comment]
was steht in der console (F12)?

**Comment by guergen1** [comment]
Ich kann den Fehler nicht mehr reproduzieren, jetzt ist alles korrekt dargestellt.
