### ISSUE TITLE
Fehlermeldung bei Konfiguration bearbeiten

### ISSUE THREAD

**Issue by daniel-lo** [Scrounger/ioBroker.linkeddevices#70]
Hallo, wenn ich in der Instanz Linkeddevices ein vorhandenes Gerät editieren möchte erhalte ich eine Fehlermeldung:

![grafik](https://user-images.githubusercontent.com/4311558/121125822-78bf1300-c827-11eb-8a1d-3d5fb20a2b20.png)

**Comment by daniel-lo** [comment]
linkeddevices.0 | 2021-06-08 07:28:03.728 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | -- | --
linkeddevices.0 | 2021-06-08 07:28:03.728 | warn | Object  linkeddevices.0.echo_wohnzimmer.ACTUAL is invalid: obj.common.type has  an invalid value (state) but has to be one of number, string, boolean,  array, object, mixed, file, json
linkeddevices.0 | 2021-06-08 07:28:03.675 | warn | This object will not be created in future versions. Please report this to the developer.
linkeddevices.0 | 2021-06-08 07:28:03.675 | warn | Object  linkeddevices.0.echo_schlafzimmer.ACTUAL is invalid: obj.common.type  has an invalid value (state) but has to be one of number, string,  boolean, array, object, mixed, file, json
linkeddevices.0 | 2021-06-08 07:28:03.242 | warn | This object will not be created in future versions. Please report this to the developer.
linkeddevices.0 | 2021-06-08 07:28:03.242 | warn | Object  linkeddevices.0.echo_schlafzimmer.ACTUAL is invalid: obj.common.type  has an invalid value (state) but has to be one of number, string,  boolean, array, object, mixed, file, json
linkeddevices.0 | 2021-06-08 07:28:03.235 | warn | This object will not be created in future versions. Please report this to the developer.
linkeddevices.0 | 2021-06-08 07:28:03.234 | warn | Object  linkeddevices.0.echo_wohnzimmer.ACTUAL is invalid: obj.common.type has  an invalid value (state) but has to be one of number, string, boolean,  array, object, mixed, file, json

**Comment by Scrounger** [comment]
Support für admin5 noch nicht vorhanden.

siehe #67 und #65

**Comment by Fontheweg** [comment]
Hast Du eine Idee ab wann ungefähr das Release mit Support für Admin 5 kommen wird?

**Comment by daniel-lo** [comment]
@Fontheweg Du kannst im alten Admin alles einrichten und dann zum neuen zurück schalten.

**Comment by Fontheweg** [comment]
@daniel-lo danke für den Tipp, das beantwortet allerdings nicht meine Frage.

**Comment by bjaesch912** [comment]
> @Fontheweg Du kannst im alten Admin alles einrichten und dann zum neuen zurück schalten.

Wie funktioniert das? Also wie schalte ich hin und zurück?

**Comment by daes10** [comment]
Siehe offizielles Forum. Wenn man auf Admin 5 updatet, sieht man dort was man alles beachten sollte. Da steht auch das der linked devices Adapter noch nicht für Admin 5 gemacht ist und wie man auf die alte Oberfläche kommt.

Einfach zweite Instanz vom Admin Adapter anlegen, unter anderem Port und den Haken in den Einstellungen des neuen Admin Adapters  "alte Benutzeroberfläche" setzen.

[https://forum.iobroker.net/topic/46813/admin-v5-jetzt-im-stable/2](url)

**Comment by daniel-lo** [comment]
@daes10 
@bjaesch912 
Eine zweite Instanz ist bei mir nicht nötig .. die Checkbox tut es bereits.
