### ISSUE TITLE
Devices können nicht mehr hinzugefügt werden

### ISSUE THREAD

**Issue by GreatEMU** [Scrounger/ioBroker.linkeddevices#74]
**Describe the bug**  
Nach dem Update das Admin-Adapters im ioBroker auf Version 5, befindet sich bei den Eigenschaften zu einem Objekt kein Tab mehr zum verlinken der Device.

**Comment by SevenUp666** [comment]
https://github.com/ioBroker/ioBroker.admin/issues/692#issuecomment-857472871

**Comment by nevermind2001** [comment]
Any News on that Issue?

**Comment by Pittini** [comment]
Any news? Its really annoying, I have now exactly the situation linked devices should prevent - some devices in linked devices and some normally, also a mixed state, 'caus I can not add new devices.

**Comment by Scrounger** [comment]
It will be fixed, but i have no time at the moment.
Current work around, activate old gui in admin adapter, create / edit linkeddevices custom objects and switch back to new gui.
