### ISSUE TITLE
Fehlende Einstellung unter Admin

### ISSUE THREAD

**Issue by AFPass** [Scrounger/ioBroker.linkeddevices#76]
Hallo,
ich habe gerade über Github die neue Version installiert.

Unter der neuen Admin Oberfläche fehlen noch einige Buttons gegenüber dem alten Admin

Alt:
![image](https://user-images.githubusercontent.com/13101074/165069156-473353bc-5600-423a-ab9e-17043ed4cf54.png)

Neu:
![image](https://user-images.githubusercontent.com/13101074/165069194-e4b50e84-df87-460d-9b43-ec138f743711.png)

**Comment by Scrounger** [comment]
Diese Funktionalität (3 Buttons) ist mit dem Admin 5 nicht mehr darstellbar, sorry.
