### ISSUE TITLE
1.5.0 lässt sich nicht updaten

### ISSUE THREAD

**Issue by guergen1** [Scrounger/ioBroker.linkeddevices#77]
Hier die Meldung nach dem Update über den Admin(sollte ja egtl installiert sein):
`$ iobroker upgrade linkeddevices@1.5.0

Update linkeddevices from @1.4.4 to @1.5.0

NPM version: 6.14.16Installing iobroker.linkeddevices@1.5.0... (System call)

+ iobroker.linkeddevices@1.5.0updated 1 package in 17.808s

92 packages are looking for funding run `npm fund` for details

upload [13] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/admin.d.ts admin.d.ts video/mp2t

upload [12] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/custom.js custom.js application/javascript

upload [11] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/custom_m.html custom_m.html text/html

upload [10] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/img/info-big.png img/info-big.png image/png

upload [9] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/index_m.html index_m.html text/html

upload [8] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/index_m.js index_m.js application/javascript

upload [7] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/jsonCustom.json jsonCustom.json application/json

upload [6] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/linkeddevices.png linkeddevices.png image/png

upload [5] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/linkeddevices_info.png linkeddevices_info.png image/png

upload [4] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/linkeddevices_missing.png linkeddevices_missing.png image/png

upload [3] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/linkeddevices_small.png linkeddevices_small.png image/png

upload [2] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/style.css style.css text/css

upload [1] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/words.js words.js application/javascript

upload [0] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/words_material.js words_material.js application/javascript

Process exited with code 0`

Hier das Update per SSH:
`Would you like to upgrade linkeddevices from @1.4.4 to @1.5.0 now? [(y)es, (n)o]: y
Update linkeddevices from @1.4.4 to @1.5.0
NPM version: 6.14.16
Installing iobroker.linkeddevices@1.5.0... (System call)
+ iobroker.linkeddevices@1.5.0
updated 1 package in 17.206s

92 packages are looking for funding
  run `npm fund` for details

upload [13] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/admin.d.ts admin.d.ts video/mp2t
upload [12] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/custom.js custom.js application/javascript
upload [11] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/custom_m.html custom_m.html text/html
upload [10] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/img/info-big.png img/info-big.png image/png
upload [9] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/index_m.html index_m.html text/html
upload [8] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/index_m.js index_m.js application/javascript
upload [7] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/jsonCustom.json jsonCustom.json application/json
upload [6] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/linkeddevices.png linkeddevices.png image/png
upload [5] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/linkeddevices_info.png linkeddevices_info.png image/png
upload [4] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/linkeddevices_missing.png linkeddevices_missing.png image/png
upload [3] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/linkeddevices_small.png linkeddevices_small.png image/png
upload [2] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/style.css style.css text/css
upload [1] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/words.js words.js application/javascript
upload [0] linkeddevices.admin /opt/iobroker/node_modules/iobroker.linkeddevices/admin/words_material.js words_material.js application/javascript
iob@iob:~$
`

Version ist immer noch 1.4.4 !

**Comment by Scrounger** [comment]
zeigt nur die falsche nummer, habs behoben mit 1.5.1
