### ISSUE TITLE
"Prefix for id of linked devices" wird nicht gespeichert

### ISSUE THREAD

**Issue by AFPass** [Scrounger/ioBroker.linkeddevices#78]
"Prefix for id of linked devices" wird nicht gespeichert

![image](https://user-images.githubusercontent.com/13101074/165768659-c6d7a4c1-8363-4d68-b804-dbdcb64d0bb0.png)

Legt ein Linkeddevice wie folgt an:
{
  "type": "state",
  "common": {
    "name": "Illuminance",
    "type": "number",
    "unit": "lux",
    "read": true,
    "write": false,
    "role": "value.brightness",
    "custom": {
      "linkeddevices.0": {
        "enabled": true,
        "number_convertTo": "",
        "number_to_duration_format": "dd[T] hh[h] mm[m]",
        "number_to_datetime_format": "dd[T] hh[h] mm[m]",
        "boolean_convertTo": "",
        "string_convertTo": "",
        "linkedId": "Grundstueck.Schuppen.illuminance",
        "_prefixId": "",
        "_stateId": "illuminance",
        "mergeSettingsOnRestart": true
      }
    }
  },
  "native": {},
  "_id": "zigbee.0.04cf8cdf3c7f2a79.illuminance",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1651154172406
}

Obwohl ich Grundstueck.Schuppen.Unten.Helligkeit angegeben habe.

Ändere ich den Pfad "Grundstueck.Schuppen" noch einmal manuell, kann ich nicht Speichern da der Button aus gegraut ist.

**Comment by Scrounger** [comment]
Du musst leider immer Enter drücken, damit die Eingabe in prefix id übernommen wird.

Hab duzu bereits ein issue im admin aufgemacht:
https://github.com/ioBroker/ioBroker.admin/issues/1442

**Comment by ykuendig** [comment]
Leider ist das noch nicht ganz überstanden.
Das neue Admin-Update (teste gerade mit 6) macht nun zwar ein Update der ID nach dem Prefix ohne Enter.
Dafür wird nun aber die eigentliche ID nicht mehr angehängt.
Hmmm
