### ISSUE TITLE
Checkboxen löscht Textfeld

### ISSUE THREAD

**Issue by AFPass** [Scrounger/ioBroker.linkeddevices#79]
Aktiviere / Deaktiviere ich eine Checkbox "mergeSettingsOnRestart" oder "Aktiviert", wird das Feld "prefix for id of linked object" geleert.

**Comment by Scrounger** [comment]
Tatsache, hab ich natürlich nicht getestet. 
Das muss im Admin Adapter gefixt werden, bitte mach dort ein Ticket auf. 
Sorry aber der neue Custom Dialog lässt einem keine Möglichkeit das selbst zu beheben.

**Comment by PalmManiac** [comment]
Ist der Admin-Adapter auch dafür verantwortlich, dass  in den Feldern schon getätigte Einträge nicht mehr sortiert angezeigt werden, wenn man das Feld anklickt? Im Moment wird dort alles durcheinander aufgelistet, was die Suche und Eingabe sehr erschwert.

**Comment by Scrounger** [comment]
@PalmManiac 
Mach mal einen Screenshot, weiß nicht was du genau meinst

**Comment by PalmManiac** [comment]
@Scrounger Ich meine die Verlaufliste der eingegeben Pfade oder Datenpunkte, wenn man in das leere Feld klickt,

![image](https://user-images.githubusercontent.com/84145136/166140894-bc10f1a8-8aeb-44f9-abec-22972d32bbec.png)

**Comment by Apollon77** [comment]
@Scrounger Könntest Du das Admin issue bitte mit ein bissl mehr "fleisch" anreichern? Was soll Bluefox denn damit anfangen ausser zu raten. Also: Was tut die Checklbox. link zum json custom config. was ist das was passieren soll, was passiert stattdessen.

**Comment by Scrounger** [comment]
@PalmManiac 
ok die Liste sollte eigentlich sortiert sein, mach dazu bitte ein extra Issue auf, hat nichts mit der Checkbox zu tun.

@Apollon77 
mach ich

**Comment by Scrounger** [comment]
fix siehe https://github.com/ioBroker/ioBroker.admin/issues/1446
