### ISSUE TITLE
Keine Ordnerstruktur mehr mit Admin V6

### ISSUE THREAD

**Issue by ghost** [Scrounger/ioBroker.linkeddevices#83]
Mit dem Update auf Admin V6 ist es nicht mehr möglich eigene Ordnerstrukturen mit Linkeddevice im IoBroker aufzubauen.

Bisher konnte man Unterordner erstellen indem man im Pefix die Struktur mit Punkten definierte. Zum Beispiel:

Leuchten.Badezimmer.Decke.Einbauspots

Somit wurde im Root des Linkeddevice ein ordner "Leuchten" erstellt der den Unterordner "Badezimmer" enthielt usw.

**Comment by klein0r** [comment]
Geht schon noch. Allerdings nur im Expterten-Modus. Und das ist auch richtig so, da viele früher in den Strukturen von anderen Adaptern eigene Datenpunkte angelegt haben, was nie so gedacht war und nicht zu empfehlen ist.

**Comment by ninja-warrior** [comment]
@klein0r: Naja, aber seit Admin V6 ist die Orderstruktur zumindest bei mir nur noch über einen Workaround möglich. Die Kombination aus Prefix + ID ( = Datenpunkt) funktioniert bei mir nicht mehr. Ich muss in die ID den vollständigen Datenpunkt eintragen. Das war in älteren Versionen nicht so. 

Kann das Verhalten jemand bestätigen?

**Comment by guergen1** [comment]
Normal konnte man die Struktur von Linkeddevices anlegen lassen, das geht im Moment bei mir auch nicht

**Comment by Scrounger** [comment]
fix in Admin V6.2.18
